### PR TITLE
Ensure we have channel data before removing it.

### LINKED ISSUE #35: If our client parts, but we do not have the channel in state, the app will crash
See https://github.com/matrix-org/node-irc/blob/e1f7f76afbf5ca06ca050a19551cb35ea0294b20/lib/irc.js#L551-L569

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #35

### CODE REVIEW

File: lib/irc.js [hunk 1]
```diff
@@ -756,6 +754,16 @@ Client.prototype.chanData = function(name, create) {
     return this.chans[key];
 };
 
+Client.prototype.removeChanData = function(name) {
+    const key = name.toLowerCase();
+    // Sometimes we can hit a race where we will get a PART about outselves before we
```
Comment (turt2live) [inline lib/irc.js]: do we need to add similar logic to joins to avoid them adding the channel back?

Comment (turt2live) [inline lib/irc.js]:
```suggestion
    // Sometimes we can hit a race where we will get a PART about ourselves before we
```

Comment (Half-Shot) [reply lib/irc.js]: We shouldn't, joins should always create state.
