### PR TITLE
Handle no-nick whois response

### LINKED ISSUE #68: Cannot read property 'nick' of undefined
```
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]: 2021-06-07 00:00:19 INFO:BridgedClient 
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]: FATAL EXCEPTION
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]: TypeError: Cannot read property 'nick' of undefined
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at Client.callbackWrapper (/opt/c3985ad0-be13-11eb-856f-1da0e30d2c5a-live/matrix-appservice-irc-develop-26-05-21-libera/node_modules/matrix-org-irc/lib/irc.js:1270:26)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at Client.emit (events.js:388:22)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at Client.emit (domain.js:470:12)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at Client.onRaw (/opt/c3985ad0-be13-11eb-856f-1da0e30d2c5a-live/matrix-appservice-irc-develop-26-05-21-libera/node_modules/matrix-org-irc/lib/irc.js:798:34)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at Client.emit (events.js:388:22)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at Client.emit (domain.js:470:12)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at /opt/c3985ad0-be13-11eb-856f-1da0e30d2c5a-live/matrix-appservice-irc-develop-26-05-21-libera/node_modules/matrix-org-irc/lib/irc.js:1068:26
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at Array.forEach (<anonymous>)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at TLSSocket.<anonymous> (/opt/c3985ad0-be13-11eb-856f-1da0e30d2c5a-live/matrix-appservice-irc-develop-26-05-21-libera/node_modules/matrix-org-irc/lib/irc.js:1062:19)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at TLSSocket.emit (events.js:376:20)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at TLSSocket.emit (domain.js:470:12)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at addChunk (internal/streams/readable.js:309:12)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at readableAddChunk (internal/streams/readable.js:280:11)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]: 2021-06-07 00:00:19 ERROR:main FATAL EXCEPTION
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]: 2021-06-07 00:00:19 ERROR:main TypeError: Cannot read property 'nick' of undefined
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at Client.callbackWrapper (/opt/c3985ad0-be13-11eb-856f-1da0e30d2c5a-live/matrix-appservice-irc-develop-26-05-21-libera/node_modules/matrix-org-irc/lib/irc.js:1270:26)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at Client.emit (events.js:388:22)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at Client.emit (domain.js:470:12)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at Client.onRaw (/opt/c3985ad0-be13-11eb-856f-1da0e30d2c5a-live/matrix-appservice-irc-develop-26-05-21-libera/node_modules/matrix-org-irc/lib/irc.js:798:34)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at Client.emit (events.js:388:22)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at Client.emit (domain.js:470:12)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at /opt/c3985ad0-be13-11eb-856f-1da0e30d2c5a-live/matrix-appservice-irc-develop-26-05-21-libera/node_modules/matrix-org-irc/lib/irc.js:1068:26
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at Array.forEach (<anonymous>)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at TLSSocket.<anonymous> (/opt/c3985ad0-be13-11eb-856f-1da0e30d2c5a-live/matrix-appservice-irc-develop-26-05-21-libera/node_modules/matrix-org-irc/lib/irc.js:1062:19)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at TLSSocket.emit (events.js:376:20)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at TLSSocket.emit (domain.js:470:12)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at addChunk (internal/streams/readable.js:309:12)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at readableAddChunk (internal/streams/readable.js:280:11)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]:     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]: 2021-06-07 00:00:19 ERROR:main Terminating (exitcode=1)
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]: 2021-06-07 00:00:19 DEBUG:ClientPool Added pending nick: repo
Jun  7 00:00:19 eu-west-2-ircbridges liberairc[11753]: 2021-06-07 00:00:19 DEBUG:MetricsWorker Request for /metrics
```

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #68

### CODE REVIEW

File: src/irc.ts [hunk 1]
```diff
@@ -351,7 +351,11 @@ export class Client extends EventEmitter {
             // If this connection is using SASL, we don't want to emit this until they are authenticated.
             this.emit('registered');
         }
-        this.whois(this.nick, (args) => {
+        this.whois(this.currentNick, (args) => {
+            if (!args) {
```
Comment (Half-Shot) [inline src/irc.ts:355]: This isn't catestrophic, we do set these values above but it's still a bit bad if we can't whois ourself
