### PR TITLE
Fix chanlist in nick change events

### LINKED ISSUE #1776: Nick changes on IRC are not recognized
Doing `/nick mynewnickname` on IRC does not do anything to a bridged Matrix room, until `mynewnickname` says something. This then makes `mynewnickname (IRC)` join the Matrix room. It does not remove `myoldnickname` from the matrix room though. This is especially remarkable with IRC nickchanges after network failures.

When the IRC client disconnects for a short time and then reconnects, the original `nickname` is blocked for a while, so the client then connects using e.g. `nickname_`. To get the old nickname back, there is e.g. [keepnick.py](https://weechat.org/scripts/source/keepnick.py.html/) to hold on until the "nickstealer" left the network and then automatically renames us back to `nickname`.

So while `@irc_nickname:server.tld` is back on track, the intermediate user named `@irc_nickname_:server.tld` stays in the Matrix room.

This has been the case with quits/parts as well until recently. But for a couple of weeks now, quits/parts are correctly recognized, and the corresponding Matrix user is removed from the room. Will this work with nickchanges as well?

I am seeing this using BridgeVersion: 1.0.1 bridging Synapse 1.91.0 with Quakenet.

### PR DESCRIPTION
**Pull request by jkhsjdhjs**
This fixes nick changes not being bridged to matrix, due to the chanlist being empty in nick change events.

Fix https://github.com/matrix-org/matrix-appservice-irc/issues/1776

### CODE REVIEW

**Comment by jkhsjdhjs** [comment]
@tadzik friendly ping

**Comment by tadzik** [comment]
Having tested it against the IRC bridge, it doesn't seem to solve the issue – both with and without the patch the event fires in https://github.com/matrix-org/matrix-appservice-irc/blob/develop/src/irc/BridgedClient.ts#L294. It then never does anything because `this.nick` is set to the connection instance's nick (could be `MatrixBot` or one of the matrix users' ghosts).

Did it fix anything in your case? Is there any situation when this should fire but doesn't? Could you share steps to reproduce this?

**Comment by jkhsjdhjs** [comment]
That's a different event I think, can't tell exactly because I no longer have access to my dev instance, but I think this is the event that isn't triggered currently: https://github.com/matrix-org/matrix-appservice-irc/blob/7edfec7bd45cf3695904be7da3633d2e4475f90c/src/irc/IrcEventBroker.ts#L399

Or to be precise: The event handler is triggered, the `nick` event is emitted, but chans is empty and thus the matrix puppets aren't updated.

To reproduce you can just have an irc user (not a puppet) change their nick. The corresponding matrix puppet will not be updated.

#103 attempted to fix this previously and initially had it correct, but then committed this to fix the typecheckers complaints: https://github.com/matrix-org/node-irc/pull/103/commits/955f6d46a9d727ab418c9d42e09a5616dfeba311

This commit, however, doesn't make any sense and actually breaks the state tracking, as it saves booleans instead of channel lists in the `nickChannel` map. This PR reverts the commit and fixes the typecheckers complaints this way: https://github.com/matrix-org/node-irc/pull/117/commits/0f1caa2ff6b1998dde89e5699e93b0cbfda00ce6

File: src/irc.ts [hunk 1]
```diff
@@ -630,9 +630,8 @@ export class Client extends (EventEmitter as unknown as new () => TypedEmitter<C
 
         // finding what channels a user is in
         this.state.chans.forEach((nickChannel, channame) => {
-            const chanUser = message.nick && nickChannel.users.get(message.nick);
-            if (message.nick && chanUser) {
```
Comment (f0x52) [inline src/irc.ts:634]: This if-statement checks if `chanUser` is truthy, and an empty string is not.
So nick change events don't get past this check, if the user has no channel modes set (normal user).
The event still fires in matrix-appservice-irc, but with a channel list that's always empty, so nothing happens.

**Comment by f0x52** [comment]
I was able to reproduce nick changes not getting bridged properly, and this PR correctly fixes the issue by checking if the old nick was in the userlist for the channel, instead of relying on the stored usermode string being truthy (an empty string isn't).

**Comment by jkhsjdhjs** [comment]
@tadzik

**Comment by tadzik** [comment]
Okay; gave it a fresh try and experimented a bit, since it was clearly something wrong with me here :)

Turns out that for this to work, `membershipLists.global.ircToMatrix.incremental` needs to be enabled. In that case the patch indeed fixes the nick change problem.
